# Generated by Django 4.2.3 on 2023-07-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='related_post',
            new_name='corresponding_post',
        ),
    ]
